// raylib's textures_raw_data example, Copyright (c) 2015-2025 Ramon Santamaria (@raysan5), under the
// zlib license, written again for the flat API.

using System.Runtime.InteropServices;
using static Engine.Engine3D;

namespace Engine.Examples;

public static class TexturesRawData
{
    public static void Run()
    {
        const int screenWidth = 800;
        const int screenHeight = 450;

        InitWindow(screenWidth, screenHeight, "[textures] raw data");

        // Load RAW image data (512x512, 32bit RGBA, no file header)
        Image fudesumiRaw = LoadImageRaw("resources/fudesumi.raw", 384, 512, PixelFormat.UncompressedR8G8B8A8, 0);
        Texture2D fudesumi = LoadTextureFromImage(fudesumiRaw);  // Upload CPU (RAM) image to GPU (VRAM)
        UnloadImage(fudesumiRaw);                                // Unload CPU (RAM) image data

        // Generate a checked texture by code
        int imWidth = 960;
        int imHeight = 480;

        // An array to store pixels data (Color type)
        Color[] pixels = new Color[imWidth*imHeight];

        for (int y = 0; y < imHeight; y++)
        {
            for (int x = 0; x < imWidth; x++)
            {
                if (((x/32+y/32)/1)%2 == 0) pixels[y*imWidth + x] = Color.Orange;
                else pixels[y*imWidth + x] = Color.Gold;
            }
        }

        // Load pixels data into an image structure and create texture
        // NOTE: An image here is always four bytes a pixel, red, green, blue and alpha, as a Color
        // is laid out, so the colors' bytes are its data and it has no format to set
        Image checkedIm = new(MemoryMarshal.AsBytes(pixels.AsSpan()).ToArray(), imWidth, imHeight);

        Texture2D checkedTex = LoadTextureFromImage(checkedIm);
        UnloadImage(checkedIm);         // Unload CPU (RAM) image data (pixels)

        SetTargetFPS(60);

        while (!WindowShouldClose())
        {
            BeginDrawing();

                ClearBackground(Color.RayWhite);

                DrawTexture(checkedTex, screenWidth/2 - checkedTex.Width/2, screenHeight/2 - checkedTex.Height/2, Fade(Color.White, 0.5f));
                DrawTexture(fudesumi, 430, -30, Color.White);

                DrawText("CHECKED TEXTURE ", 84, 85, 30, Color.Brown);
                DrawText("GENERATED by CODE", 72, 148, 30, Color.Brown);
                DrawText("and RAW IMAGE LOADING", 46, 210, 30, Color.Brown);

                DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, Color.Brown);

            EndDrawing();
        }

        UnloadTexture(fudesumi);    // Texture unloading
        UnloadTexture(checkedTex);  // Texture unloading

        CloseWindow();
    }
}
