<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Engine.Examples</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\3DEngine\3DEngine.csproj" />
        <ProjectReference Include="..\3DEngine.Generator\3DEngine.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
