using Engine.Examples;

// Each example is a program of its own, in the manner of raylib's examples, and this file picks
// one by name: dotnet run --project 3DEngine.Examples -- core_3d_camera_free
var examples = new Dictionary<string, Action>
{
    ["core_basic_window"] = CoreBasicWindow.Run,
    ["core_3d_camera_fps"] = Core3DCameraFps.Run,
    ["core_keyboard_testbed"] = CoreKeyboardTestbed.Run,
    ["core_input_actions"] = CoreInputActions.Run,
    ["core_undo_redo"] = CoreUndoRedo.Run,
    ["core_random_sequence"] = CoreRandomSequence.Run,
    ["core_basic_screen_manager"] = CoreBasicScreenManager.Run,
    ["core_storage_values"] = CoreStorageValues.Run,
    ["core_custom_logging"] = CoreCustomLogging.Run,
    ["core_window_letterbox"] = CoreWindowLetterbox.Run,
    ["core_viewport_scaling"] = CoreViewportScaling.Run,
    ["core_2d_camera_split_screen"] = Core2DCameraSplitScreen.Run,
    ["core_input_multitouch"] = CoreInputMultitouch.Run,
    ["core_input_gestures_testbed"] = CoreInputGesturesTestbed.Run,
    ["core_input_virtual_controls"] = CoreInputVirtualControls.Run,
    ["core_delta_time"] = CoreDeltaTime.Run,
    ["core_input_keys"] = CoreInputKeys.Run,
    ["core_input_mouse"] = CoreInputMouse.Run,
    ["core_input_mouse_wheel"] = CoreInputMouseWheel.Run,
    ["core_3d_camera_mode"] = Core3DCameraMode.Run,
    ["core_3d_camera_split_screen"] = Core3DCameraSplitScreen.Run,
    ["core_3d_picking"] = Core3DPicking.Run,
    ["core_world_screen"] = CoreWorldScreen.Run,
    ["core_window_should_close"] = CoreWindowShouldClose.Run,
    ["core_random_values"] = CoreRandomValues.Run,
    ["core_scissor_test"] = CoreScissorTest.Run,
    ["core_smooth_pixelperfect"] = CoreSmoothPixelperfect.Run,
    ["core_render_texture"] = CoreRenderTexture.Run,
    ["core_text_file_loading"] = CoreTextFileLoading.Run,
    ["core_2d_camera"] = Core2DCamera.Run,
    ["core_2d_camera_platformer"] = Core2DCameraPlatformer.Run,
    ["core_2d_camera_mouse_zoom"] = Core2DCameraMouseZoom.Run,
    ["core_drop_files"] = CoreDropFiles.Run,
    ["audio_raw_stream"] = AudioRawStream.Run,
    ["audio_mixed_processor"] = AudioMixedProcessor.Run,
    ["audio_stream_effects"] = AudioStreamEffects.Run,
    ["core_3d_camera_free"] = Core3DCameraFree.Run,
    ["core_3d_camera_first_person"] = Core3DCameraFirstPerson.Run,
    ["core_input_gamepad"] = CoreInputGamepad.Run,
    ["core_window_toggles"] = CoreWindowToggles.Run,
    ["core_window_flags"] = CoreWindowFlags.Run,
    ["core_highdpi_demo"] = CoreHighdpiDemo.Run,
    ["core_highdpi_testbed"] = CoreHighdpiTestbed.Run,
    ["core_monitor_detector"] = CoreMonitorDetector.Run,
    ["core_custom_frame_control"] = CoreCustomFrameControl.Run,
    ["core_directory_files"] = CoreDirectoryFiles.Run,
    ["core_clipboard_text"] = CoreClipboardText.Run,
    ["core_compute_hash"] = CoreComputeHash.Run,
    ["shapes_basic_shapes"] = ShapesBasicShapes.Run,
    ["shapes_bouncing_ball"] = ShapesBouncingBall.Run,
    ["shapes_colors_palette"] = ShapesColorsPalette.Run,
    ["shapes_logo_raylib"] = ShapesLogoRaylib.Run,
    ["shapes_logo_raylib_anim"] = ShapesLogoRaylibAnim.Run,
    ["shapes_rectangle_scaling"] = ShapesRectangleScaling.Run,
    ["shapes_lines_bezier"] = ShapesLinesBezier.Run,
    ["shapes_collision_area"] = ShapesCollisionArea.Run,
    ["shapes_following_eyes"] = ShapesFollowingEyes.Run,
    ["shapes_easings_ball"] = ShapesEasingsBall.Run,
    ["shapes_easings_box"] = ShapesEasingsBox.Run,
    ["shapes_easings_rectangles"] = ShapesEasingsRectangles.Run,
    ["shapes_easings_testbed"] = ShapesEasingsTestbed.Run,
    ["shapes_digital_clock"] = ShapesDigitalClock.Run,
    ["shapes_bullet_hell"] = ShapesBulletHell.Run,
    ["shapes_double_pendulum"] = ShapesDoublePendulum.Run,
    ["shapes_dashed_line"] = ShapesDashedLine.Run,
    ["shapes_vector_angle"] = ShapesVectorAngle.Run,
    ["shapes_clock_of_clocks"] = ShapesClockOfClocks.Run,
    ["shapes_mouse_trail"] = ShapesMouseTrail.Run,
    ["shapes_simple_particles"] = ShapesSimpleParticles.Run,
    ["shapes_starfield_effect"] = ShapesStarfieldEffect.Run,
    ["shapes_lines_drawing"] = ShapesLinesDrawing.Run,
    ["shapes_math_angle_rotation"] = ShapesMathAngleRotation.Run,
    ["shapes_ball_physics"] = ShapesBallPhysics.Run,
    ["shapes_penrose_tile"] = ShapesPenroseTile.Run,
    ["shapes_drag_puzzle"] = ShapesDragPuzzle.Run,
    ["shapes_ellipse_collision"] = ShapesEllipseCollision.Run,
    ["shapes_polygon_lines"] = ShapesPolygonLines.Run,
    ["shapes_ring_drawing"] = ShapesRingDrawing.Run,
    ["shapes_circle_sector_drawing"] = ShapesCircleSectorDrawing.Run,
    ["shapes_rounded_rectangle_drawing"] = ShapesRoundedRectangleDrawing.Run,
    ["shapes_recursive_tree"] = ShapesRecursiveTree.Run,
    ["shapes_triangle_strip"] = ShapesTriangleStrip.Run,
    ["shapes_outlines_thickness"] = ShapesOutlinesThickness.Run,
    ["shapes_hilbert_curve"] = ShapesHilbertCurve.Run,
    ["shapes_splines_drawing"] = ShapesSplinesDrawing.Run,
    ["shapes_pie_chart"] = ShapesPieChart.Run,
    ["shapes_kaleidoscope"] = ShapesKaleidoscope.Run,
    ["shapes_math_sine_cosine"] = ShapesMathSineCosine.Run,
    ["shapes_outlines_testbed"] = ShapesOutlinesTestbed.Run,
    ["shapes_rlgl_color_wheel"] = ShapesRlglColorWheel.Run,
    ["shapes_rectangle_advanced"] = ShapesRectangleAdvanced.Run,
    ["shapes_rlgl_triangle"] = ShapesRlglTriangle.Run,
    ["shapes_top_down_lights"] = ShapesTopDownLights.Run,
    ["textures_basic"] = TexturesBasic.Run,
    ["textures_render_target"] = TexturesRenderTarget.Run,
    ["textures_image_drawing"] = TexturesImageDrawing.Run,
    ["textures_mipmaps"] = TexturesMipmaps.Run,
    ["textures_logo_raylib"] = TexturesLogoRaylib.Run,
    ["textures_image_loading"] = TexturesImageLoading.Run,
    ["textures_to_image"] = TexturesToImage.Run,
    ["textures_image_rotate"] = TexturesImageRotate.Run,
    ["textures_srcrec_dstrec"] = TexturesSrcrecDstrec.Run,
    ["textures_sprite_animation"] = TexturesSpriteAnimation.Run,
    ["textures_background_scrolling"] = TexturesBackgroundScrolling.Run,
    ["textures_image_generation"] = TexturesImageGeneration.Run,
    ["textures_image_text"] = TexturesImageText.Run,
    ["textures_particles_blending"] = TexturesParticlesBlending.Run,
    ["textures_npatch_drawing"] = TexturesNpatchDrawing.Run,
    ["textures_sprite_button"] = TexturesSpriteButton.Run,
    ["textures_sprite_explosion"] = TexturesSpriteExplosion.Run,
    ["textures_blend_modes"] = TexturesBlendModes.Run,
    ["textures_gif_player"] = TexturesGifPlayer.Run,
    ["textures_image_channel"] = TexturesImageChannel.Run,
    ["textures_image_kernel"] = TexturesImageKernel.Run,
    ["textures_sprite_stacking"] = TexturesSpriteStacking.Run,
    ["textures_clipboard_image"] = TexturesClipboardImage.Run,
    ["textures_tiled_drawing"] = TexturesTiledDrawing.Run,
    ["textures_mouse_painting"] = TexturesMousePainting.Run,
    ["textures_fog_of_war"] = TexturesFogOfWar.Run,
    ["textures_screen_buffer"] = TexturesScreenBuffer.Run,
    ["textures_cellular_automata"] = TexturesCellularAutomata.Run,
    ["textures_framebuffer_rendering"] = TexturesFramebufferRendering.Run,
    ["textures_bunnymark"] = TexturesBunnymark.Run,
    ["textures_polygon_drawing"] = TexturesPolygonDrawing.Run,
    ["textures_textured_curve"] = TexturesTexturedCurve.Run,
    ["textures_magnifying_glass"] = TexturesMagnifyingGlass.Run,
    ["textures_portal_window"] = TexturesPortalWindow.Run,
    ["textures_raw_data"] = TexturesRawData.Run,
    ["textures_image_processing"] = TexturesImageProcessing.Run,
    ["physics_boxes"] = PhysicsBoxes.Run,
    ["models_animation"] = ModelsAnimation.Run,
    ["models_loading"] = ModelsLoading.Run,
    ["models_mesh_generation"] = ModelsMeshGeneration.Run,
    ["models_terrain"] = ModelsTerrain.Run,
    ["models_skybox"] = ModelsSkybox.Run,
    ["models_reflection_probe"] = ModelsReflectionProbe.Run,
    ["models_morph_and_layers"] = ModelsMorphAndLayers.Run,
    ["models_stress"] = ModelsStress.Run,
    ["models_geometric_shapes"] = ModelsGeometricShapes.Run,
    ["models_box_collisions"] = ModelsBoxCollisions.Run,
    ["models_waving_cubes"] = ModelsWavingCubes.Run,
    ["models_orthographic_projection"] = ModelsOrthographicProjection.Run,
    ["models_billboard_rendering"] = ModelsBillboardRendering.Run,
    ["models_cubicmap_rendering"] = ModelsCubicmapRendering.Run,
    ["models_first_person_maze"] = ModelsFirstPersonMaze.Run,
    ["models_heightmap_rendering"] = ModelsHeightmapRendering.Run,
    ["models_rotating_cube"] = ModelsRotatingCube.Run,
    ["models_directional_billboard"] = ModelsDirectionalBillboard.Run,
    ["models_yaw_pitch_roll"] = ModelsYawPitchRoll.Run,
    ["models_loading_gltf"] = ModelsLoadingGltf.Run,
    ["models_animation_timing"] = ModelsAnimationTiming.Run,
    ["models_tesseract_view"] = ModelsTesseractView.Run,
    ["models_basic_voxel"] = ModelsBasicVoxel.Run,
    ["models_bone_socket"] = ModelsBoneSocket.Run,
    ["models_mesh_picking"] = ModelsMeshPicking.Run,
    ["models_animation_gpu_skinning"] = ModelsAnimationGpuSkinning.Run,
    ["models_textured_cube"] = ModelsTexturedCube.Run,
    ["models_rlgl_solar_system"] = ModelsRlglSolarSystem.Run,
    ["models_animation_blend_custom"] = ModelsAnimationBlendCustom.Run,
    ["models_animation_blending"] = ModelsAnimationBlending.Run,
    ["models_decals"] = ModelsDecals.Run,
    ["models_procedural_decals"] = ModelsProceduralDecals.Run,
    ["models_mesh_uv_painting"] = ModelsMeshUvPainting.Run,
    ["models_point_rendering"] = ModelsPointRendering.Run,
    ["models_loading_vox"] = ModelsLoadingVox.Run,
    ["models_loading_iqm"] = ModelsLoadingIqm.Run,
    ["models_loading_m3d"] = ModelsLoadingM3d.Run,
    ["shaders_postprocessing"] = ShadersPostprocessing.Run,
    ["shaders_model"] = ShadersModel.Run,
    ["shaders_compute_life"] = ShadersComputeLife.Run,
    ["shaders_compute_texture"] = ShadersComputeTexture.Run,
    ["shaders_bloom"] = ShadersBloom.Run,
    ["shaders_auto_exposure"] = ShadersAutoExposure.Run,
    ["shaders_particles"] = ShadersParticles.Run,
    ["shaders_shadowmap"] = ShadersShadowmap.Run,
    ["shaders_mesh_instancing"] = ShadersMeshInstancing.Run,
    ["shaders_shapes_textures"] = ShadersShapesTextures.Run,
    ["shaders_texture_outline"] = ShadersTextureOutline.Run,
    ["shaders_texture_waves"] = ShadersTextureWaves.Run,
    ["shaders_texture_rendering"] = ShadersTextureRendering.Run,
    ["shaders_texture_tiling"] = ShadersTextureTiling.Run,
    ["shaders_multi_sample2d"] = ShadersMultiSample2d.Run,
    ["shaders_simple_mask"] = ShadersSimpleMask.Run,
    ["shaders_palette_switch"] = ShadersPaletteSwitch.Run,
    ["shaders_eratosthenes_sieve"] = ShadersEratosthenesSieve.Run,
    ["shaders_julia_set"] = ShadersJuliaSet.Run,
    ["shaders_mandelbrot_set"] = ShadersMandelbrotSet.Run,
    ["shaders_raymarching_rendering"] = ShadersRaymarchingRendering.Run,
    ["shaders_ascii_rendering"] = ShadersAsciiRendering.Run,
    ["shaders_color_correction"] = ShadersColorCorrection.Run,
    ["shaders_spotlight_rendering"] = ShadersSpotlightRendering.Run,
    ["shaders_rounded_rectangle"] = ShadersRoundedRectangle.Run,
    ["shaders_hot_reloading"] = ShadersHotReloading.Run,
    ["shaders_custom_uniform"] = ShadersCustomUniform.Run,
    ["shaders_model_shader"] = ShadersModelShader.Run,
    ["shaders_basic_lighting"] = ShadersBasicLighting.Run,
    ["shaders_fog_rendering"] = ShadersFogRendering.Run,
    ["shaders_normalmap_rendering"] = ShadersNormalmapRendering.Run,
    ["shaders_basic_pbr"] = ShadersBasicPbr.Run,
    ["shaders_cel_shading"] = ShadersCelShading.Run,
    ["shaders_depth_writing"] = ShadersDepthWriting.Run,
    ["shaders_hybrid_rendering"] = ShadersHybridRendering.Run,
    ["shaders_shadowmap_rendering"] = ShadersShadowmapRendering.Run,
    ["shaders_vertex_displacement"] = ShadersVertexDisplacement.Run,
    ["shaders_depth_rendering"] = ShadersDepthRendering.Run,
    ["shaders_lights_bloom"] = ShadersLightsBloom.Run,
    ["shaders_game_of_life"] = ShadersGameOfLife.Run,
    ["shaders_rlgl_compute"] = ShadersRlglCompute.Run,
    ["shaders_lightmap_rendering"] = ShadersLightmapRendering.Run,
    ["shaders_deferred_rendering"] = ShadersDeferredRendering.Run,
    ["core_input_gestures"] = CoreInputGestures.Run,
    ["text_fonts"] = TextFonts.Run,
    ["text_input_box"] = TextInputBox.Run,
    ["text_font_sdf"] = TextFontSdf.Run,
    ["text_format_text"] = TextFormatText.Run,
    ["text_writing_anim"] = TextWritingAnim.Run,
    ["text_font_spritefont"] = TextFontSpritefont.Run,
    ["text_sprite_fonts"] = TextSpriteFonts.Run,
    ["text_font_filters"] = TextFontFilters.Run,
    ["text_unicode_ranges"] = TextUnicodeRanges.Run,
    ["text_codepoints_loading"] = TextCodepointsLoading.Run,
    ["text_words_alignment"] = TextWordsAlignment.Run,
    ["text_strings_management"] = TextStringsManagement.Run,
    ["text_rectangle_bounds"] = TextRectangleBounds.Run,
    ["text_inline_styling"] = TextInlineStyling.Run,
    ["text_3d_drawing"] = Text3DDrawing.Run,
    ["text_font_loading"] = TextFontLoading.Run,
    ["text_unicode_emojis"] = TextUnicodeEmojis.Run,
    ["audio_sound"] = AudioSound.Run,
    ["audio_sound_loading"] = AudioSoundLoading.Run,
    ["audio_sound_multi"] = AudioSoundMulti.Run,
    ["audio_sound_positioning"] = AudioSoundPositioning.Run,
    ["audio_music_stream"] = AudioMusicStream.Run,
    ["audio_stream_callback"] = AudioStreamCallback.Run,
    ["audio_amp_envelope"] = AudioAmpEnvelope.Run,
    ["audio_spectrum_visualizer"] = AudioSpectrumVisualizer.Run,
    ["gui_imgui_window"] = GuiImGuiWindow.Run,
    ["ecs_behaviors"] = EcsBehaviors.Run,
    ["ecs_mesh_entities"] = EcsMeshEntities.Run,
    ["ecs_animated_models"] = EcsAnimatedModels.Run,
    ["ecs_states"] = EcsStates.Run,
    ["ecs_physics"] = EcsPhysics.Run,
    ["scenes_level"] = ScenesLevel.Run,
};

var name = args.Length > 0 ? args[0] : "core_3d_camera_free";
if (!examples.TryGetValue(name, out var run))
{
    Console.WriteLine($"No example called '{name}'. The examples are:");
    foreach (var known in examples.Keys) Console.WriteLine($"  {known}");
    return 1;
}

Example.Current = name;
run();
return 0;

namespace Engine.Examples
{
    /// <summary>Which example is running, so an example's behaviors run only in that example.</summary>
    /// <remarks>
    /// Behaviors are discovered across the whole assembly, and every example lives in this one, so
    /// each behavior here carries a <c>[RunIf]</c> that asks this.
    /// </remarks>
    public static class Example
    {
        public static string Current { get; set; } = "";
    }
}
